services:
  web:
    image: ghcr.io/mattbox03/find-my-web:1.0.5
    restart: unless-stopped
    ports:
      - "8125:8000"
    environment:
      ENDPOINT_URL: http://apple-provider:6176
      APPLE_SETUP_TOKEN: ${APPLE_SETUP_TOKEN:-}
      GOOGLE_URL: http://google-provider:5500
      GOOGLE_TOKEN: ${GOOGLE_TOKEN:-}
      WEB_DIR: /web
      DATA_DIR: /data
      DAYS: "21"
      RETENTION_DAYS: "21"
      REFRESH_INTERVAL: "1800"
    volumes:
      - ${APP_DATA_DIR}/data/web:/data
    depends_on:
      - apple-provider
      - google-provider

  anisette:
    image: dadoum/anisette-v3-server:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/anisette:/home/Alcoholic/.config/anisette-v3

  apple-provider:
    image: ghcr.io/mattbox03/find-my-apple-provider:1.0.5
    restart: unless-stopped
    environment:
      APPLE_SETUP_PORT: "6177"
      APPLE_SETUP_TOKEN: ${APPLE_SETUP_TOKEN:-}
    volumes:
      - ${APP_DATA_DIR}/data/apple:/app/endpoint/data
    depends_on:
      - anisette

  google-provider:
    image: ghcr.io/mattbox03/find-my-google-provider:1.0.5
    restart: unless-stopped
    environment:
      AUTH_TOKEN: ${GOOGLE_TOKEN:-}
      HOST: 0.0.0.0
      PORT: "5500"
      GOOGLE_SETUP_PORT: "5501"
      GOOGLE_SECRETS_FILE: /data/Auth/secrets.json
    volumes:
      - ${APP_DATA_DIR}/data/google-auth:/data/Auth
      - ${APP_DATA_DIR}/data/google-keys:/data/KeyBackup
